nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-env.cjs
    spec: "https://raw.githubusercontent.com/aldrio/yarn-plugin-env/main/bundles/%40yarnpkg/plugin-env.js"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
